#!/bin/bash
# mounting slugalicious share, each user with thier own directory 

BASE_DIR="/home"
sudo mkdir -p "$BASE_DIR"


#-----make directory for every user------ can be re-run to update shared filesystem for new users

for user_dir in /home/*; do

    username=$(basename "$user_dir")

    if [[ -d "$user_dir" && "$username" != "ubuntu" ]]; then
        echo "Creating shared directory for user: $username"
        
        sudo mkdir -p "$BASE_DIR/$username"

        #make them owner
        sudo chown "$username:$username" "$BASE_DIR/$username"

        
        #only they can see it
        sudo chmod 700 "$BASE_DIR/$username"
    fi
done

echo "Done! Directories created in $BASE_DIR"


